fixtures:

  forge_modules:

    puppi: "example42/puppi"
    stdlib: 'puppetlabs/stdlib'

    epel: 'stahnma/epel'
    java: 'puppetlabs/java'

    concat: 'puppetlabs/concat' # Dependency for PostgreSQL
    postgresql: 'puppetlabs/postgresql'
    postgis: 'camptocamp/postgis'

    firewall: 'puppetlabs/firewall'

    tomcat: 'puppetlabs/tomcat'
    apache: 'puppetlabs/apache'

  symlinks:
    geoserver: "#{source_dir}"
